In [1]:
import numpy as np
char_arr=np.array(['a','b','c'])
char_arr

array(['a', 'b', 'c'], dtype='<U1')

In [2]:
ch_arr2=np.array(["supervised","unsupervised","sEMI-SUPERVISED","reinforcement"])
low_arr=np.char.lower(ch_arr2)
low_arr

array(['supervised', 'unsupervised', 'semi-supervised', 'reinforcement'],
      dtype='<U15')

In [3]:
cleaned_arr=np.char.replace(low_arr,"-"," ")
cleaned_arr

array(['supervised', 'unsupervised', 'semi supervised', 'reinforcement'],
      dtype='<U15')

In [4]:
arr1=np.array([1,2,3,4])
arr1.dtype

dtype('int32')

In [5]:
char_arr.dtype

dtype('<U1')

In [12]:
array8=np.array([1,2,3,4],dtype="float64")
array8

array([1., 2., 3., 4.])

In [13]:
array2conv=array8.astype('f')
array2conv

array([1., 2., 3., 4.], dtype=float32)

In [14]:
array7conv=array2conv.astype('i')
array7conv

array([1, 2, 3, 4], dtype=int32)

In [15]:
char_conv=char_arr.astype('i')
char_conv

ValueError: invalid literal for int() with base 10: 'a'

In [16]:
ars1=np.ones(3)
ars1

array([1., 1., 1.])

In [17]:
ars2=np.zeros(3)
ars2

array([0., 0., 0.])

In [19]:
ars3=np.random.random(3)
ars3

array([0.19976098, 0.32029257, 0.65426564])

In [21]:
ars3=np.random.random(3)
ars3

array([0.57239712, 0.45554265, 0.47647443])

In [22]:
ars2=np.zeros(3)
ars2

array([0., 0., 0.])

In [25]:
ars=np.zeros((2,2),dtype='i')
ars

array([[0, 0],
       [0, 0]], dtype=int32)

In [28]:
ars4=np.zeros((3,2),dtype='f')
ars4

array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)

In [30]:
ars5=np.random.random((3,2))
ars5

array([[0.11418856, 0.8651167 ],
       [0.10904002, 0.81694587],
       [0.52751081, 0.9631815 ]])

In [31]:
dimones=np.ones((4,3,2))
dimones.ndim

3

In [34]:
dimone=dimones.astype('i')
dimone

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]], dtype=int32)

In [37]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[11,12,13],[14,15,16]])
add=ar1+ar2
print(add)

[[12 14 16]
 [18 20 22]]


In [38]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[11,12,13],[14,15,16]])
sub=ar1-ar2
print(sub)

[[-10 -10 -10]
 [-10 -10 -10]]


In [39]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[11,12,13],[14,15,16]])
mul=ar1*ar2
print(mul) 

[[11 24 39]
 [56 75 96]]


In [40]:
ar1=np.array([[1,2,3],[4,5,6]])
ar2=np.array([[11,12,13],[14,15,16]])
div=ar1/ar2
print(div)

[[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]]


In [42]:
power=np.power(ar1,ar2)
print(power)

[[         1       4096    1594323]
 [ 268435456  452807053 -683606016]]


In [43]:
ar3=np.array([[1,2,3],[4,5,6]])
ar4=np.array([11,12,13])
add=ar3+ar4
print(add)

[[12 14 16]
 [15 17 19]]


In [45]:
range_arr=np.arange(0,10,3)
range_arr

array([0, 3, 6, 9])

In [46]:
range_arr=np.arange(0,10,1)
range_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
range_arr=np.arange(0,100,25)
range_arr

array([ 0, 25, 50, 75])

In [57]:
 a=np.random.randint(low=1,size=5)
a

array([0, 0, 0, 0, 0])

In [59]:
b=np.random.randint(low=1,high=6,size=(2,3))
b

array([[5, 3, 5],
       [5, 5, 3]])

In [60]:
arr=np.concatenate([ar1,ar2])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [61]:
flatarr=ar1.flatten()
flatarr

array([1, 2, 3, 4, 5, 6])

In [62]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [64]:
np.eye((5),dtype="i")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [65]:
np.info(np.ndarray.ndim)

Number of array dimensions.

Examples
--------
>>> x = np.array([1, 2, 3])
>>> x.ndim
1
>>> y = np.zeros((2, 3, 4))
>>> y.ndim
3


In [66]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [68]:
np.info(np.ndarray.flatten)

a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
